name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
      checks: write
